#!/bin/bash
#
# This script is for distributing Concord configuration files in the
# Docker-based test cluster; this script is intended to copy the configuration
# files generated by the Concord configuration generation utility's container
# to the environments in which the Concord nodes' containers run. This script
# takes arguments for the sources and destinations of the configuration files to
# move; if no arguments are provided, the default values this script uses are
# such that, if this script is launched from the concord/docker
# directory, it should move the configuration files generated for the 4-node
# Concord test cluster in Docker.
#
# Arguments:
#  1:   Path and prefix common to the configuration files as the configuration
#       generation utility has produced them; it is expected the files will have
#       names <PREFIX>1.config, <PREFIX>2.config, etc. For example, if <PREFIX>
#       is ./config-public/concord, this script will look for the configuration
#       files at ./config-public/concord1.config,
#       ./config-public/concord2.config, etc.
#  2-N: Target paths to move the configuration files to.

if [[ $# -gt 0 ]]; then
    PUBPATH=$1
    shift
else
    PUBPATH="./config-public/concord"
fi

if [[ $# -gt 0 ]]; then
    PRIVPATHS=("$@")
else
    PRIVPATHS=("./config-concord1/concord_with_hostnames.config"
               "./config-concord2/concord_with_hostnames.config"
               "./config-concord3/concord_with_hostnames.config"
               "./config-concord4/concord_with_hostnames.config")
fi

for i in $(seq 1 ${#PRIVPATHS[@]}); do
    CONFIGPATH="${PUBPATH}${i}.config"
    mv -f ${CONFIGPATH} "${PRIVPATHS[i - 1]}"
done
